services:
  backend:
    build: .
    command: sh -c "sleep 10s ; python main.py"
    depends_on:
      - db
    ports:
      - '8000:8000'


  db:
    image: mysql:9.4
    environment:
      - MYSQL_ROOT_PASSWORD=123456q
      - MYSQL_DATABASE=schedule
      - MYSQL_PORT=3306
      - MYSQL_HOST=localhost
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306

volumes:
  mysql_data:
