name: Docker Image Build (Manual)

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get release tag
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then 
            echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV 
          else 
            echo "TAG_NAME=latest" >> $GITHUB_ENV
          fi

      - name: build image
        run: docker build . -t ${{vars.DOCKER_HUB_NAME}}/${{vars.DOCKER_HUB_REPO}}:latest

      - name: push image
        run: |
          docker login -u ${{ vars.DOCKER_HUB_NAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ${{vars.DOCKER_HUB_NAME}}/${{vars.DOCKER_HUB_REPO}}:latest
          if [ "${{ github.event_name }}" == "release" ]; then 
            docker tag ${{vars.DOCKER_HUB_NAME}}/${{vars.DOCKER_HUB_REPO}}:latest ${{vars.DOCKER_HUB_NAME}}/${{vars.DOCKER_HUB_REPO}}:${{ env.TAG_NAME }}
            docker push ${{vars.DOCKER_HUB_NAME}}/${{vars.DOCKER_HUB_REPO}}:${{ env.TAG_NAME }}
          fi